### ISSUE TITLE
Unable to use dynamodb-encryption-sdk as layer

### ISSUE THREAD

**Issue by CSHaze** [aws/aws-dynamodb-encryption-python#132]
When dynamodb-encryption-sdk is added as a layer the function cannot find the module.

Steps to reproduce

1. create zip of dynamodb-encryption-sdk on an ec2 instance
2. use zip to create a lambda layer
3. use layer in a lambda function
`from dynamodb_encryption_sdk.encrypted.table import EncryptedTable`
or any other dynamodb-encryption-sdk related import

The function throws an error 
`Unable to import module 'app': No module named 'dynamodb_encryption_sdk'`

Is it not possible to use this package as a layer?

**Comment by mattsb42-aws** [comment]
Hi @CSHaze,

When you build the zip, what is the file structure? Layers require all components to be placed in a specific sub-directory[1]: `python/` for Python layers, so if you are building the zip the same way that you would for a Lambda Function zip, it will not be in the right place.

[1] https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path

**Comment by CSHaze** [comment]
Hi @mattsb42-aws,

Thank you for the help.

The steps I am using to make the zip are the same as I've used for bs4 and dateutil and those seem to work.

The steps I use to make the zip on the ec2 instance are
1. `mkdir python`
2. `cd python`
3. `pip3 install dynamodb-encryption-sdk -t .`
4. `chmod -R 755 .`
5. `zip -r ../python.zip .`

Then I download that zip using scp and upload as a layer zip file.

**Comment by mattsb42-aws** [comment]
That does not look like it should result in the expected directory structure. Does doing this change the behavior you are seeing?

```
mkdir build
cd build/
mkdir python
cd python
pip3 install dynamodb-encryption-sdk -t .
chmod -R 755 .
# move back up to build/
cd ..
# zip up python/ including the "python/" prefix
zip -r ../python.zip .
```

**Comment by CSHaze** [comment]
Thank you @mattsb42-aws!

This worked. I must have somehow done something similar to get bs4 to work and then lost the extra layer when doing the encryption-sdk.

I appreciate all the help!

**Comment by mattsb42-aws** [comment]
Awesome! Glad you got it working! :)
