### ISSUE TITLE
CPython 3.4 support

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-dynamodb-encryption-python#133]
In the next release, `pyca/cryptography` is dropping support for CPython 3.4[1]. This library is what initially set our lower bound for CPython version support, and if they are dropping support for 3.4 we should consider dropping that support as well because we rely so heavily on them.

Based on our PyPI download stats this year and the last month, I think that this is a low-risk course of action.

## Date range: 2019-01-01 - 2019-12-31

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  90.10% |   137,955 |
| 3.6      |   8.47% |    12,966 |
| 3.7      |   0.85% |     1,304 |
| null     |   0.57% |       866 |
| 3.5      |   0.01% |        14 |
| 3.4      |   0.01% |         9 |
| 3.8      |   0.00% |         1 |
| Total    |         |   153,115 |

## Date range: 2019-11-01 - 2019-11-30

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  86.56% |    22,766 |
| 3.6      |  11.22% |     2,951 |
| 3.7      |   1.86% |       489 |
| null     |   0.35% |        93 |
| 3.5      |   0.00% |         1 |
| Total    |         |    26,300 |

[1] https://github.com/pyca/cryptography/pull/5087

**Comment by texastony** [comment]
We have dropped 3.4 and 3.5 support. Closing.
