### ISSUE TITLE
Add Attested Materials provider

### ISSUE THREAD

**Issue by elliotrpmorris** [aws/aws-dynamodb-encryption-python#159]
Hi,

I have been working a lot with Nitro enclaves. Currently implementing attestation into our application where we want to call DynamoDB from within the enclave and perform decryption with attestation.

Unfortunately, boto3 doesn't support passing [the Receiptient param to the KMS API call](https://github.com/boto/botocore/issues/2271).

This can be resolved by creating a new materials provider attestation support. I am working on a solution for this would be interested to see if this could be added?

**Comment by texastony** [comment]
Howdy @elliotrpmorris ,

We apologize for the slow response.
We cannot commit to supporting an Attested Materials Provider at this time.
We do not have adding Attested Materials Provider on our road map for the Dynamo Encryption Clients.
Nor do we have any open Feature Requests for it.

While we do not have plans for this now, we may be unaware of this customer need. 
Are you still pursuing this? Or did you go down a different path?

Much Obliged,
AWS Crypto Tools

**Comment by texastony** [comment]
No Response, closing issue.
