### ISSUE TITLE
Compatibility with AWS' automatic KMS key rotation?

### ISSUE THREAD

**Issue by someboredkiddo** [aws/aws-dynamodb-encryption-python#305]
We are using the [Direct KMS Materials Provider](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/direct-kms-provider.html) to encrypt items in our dynamodb table with an AWS CMK. We were wondering what the impact of turning on automatic yearly key rotation in AWS for this CMK would be? Would the client & KMS be able to transparently encrypt/decrypt items created both before the rotation?

Ex. Assuming Application uses the AwsKmsCryptographicMaterialsProvider class
6/1/2022 Application uses CMK id 1234 to insert encrypted `Item A` into table
6/2/2022 CMK happens to be rotated automatically by AWS
6/3/2022 Application attempts to use CMK id 1234 to read `Item A`. Is this library able to transparently determine the correct key material used to decrypt `Item A` even with the AwsKmsCryptographicMaterialsProvider being initiated with just the ID of AWS KMS CMK?

We'd love to test this on our own but can't seem to trigger an automatic key rotation manually and don't want to wait a year to see if our assumption was correct :)

**Comment by alex-chew** [comment]
Hi @someboredkiddo, thanks for reaching out.

> Would the client & KMS be able to transparently encrypt/decrypt items created both before the rotation?

Yes. The DynamoDB Encryption Client identifies AWS KMS keys by their key ID, and the key ID identifies [both the "current" key material as well as previously-rotated key material (for decryption only)](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html):

> When you enable automatic key rotation for a KMS key, AWS KMS generates new cryptographic material for the KMS key every year. AWS KMS saves all previous versions of the cryptographic material in perpetuity so you can decrypt any data encrypted with that KMS key. AWS KMS does not delete any rotated key material until you [delete the KMS key](https://docs.aws.amazon.com/kms/latest/developerguide/deleting-keys.html).

So you will be able to transparently decrypt items, which were encrypted using key material that has since been rotated.
