### ISSUE TITLE
Getting null values in `desc` and `sign` fields when I fetch the item using get_item function in boto3

### ISSUE THREAD

**Issue by Abutahir12** [aws/aws-dynamodb-encryption-python#325]
Problem:

Recently I was trying to encrypt my data and store it in dynamodb table, I used Item encryptor directly, and according to the information given in this doc [aws dynamo db encryption  client](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/python-examples.html) at the end it says that, `To view the encrypted item, call the get_item method on the original table object, instead of the encrypted_table object. It gets the item from the DynamoDB table without verifying and decrypting it.`

But when I fetched the data ,l this is what I got:

> The goal was to encrypt the password

`"Item": {
            "attribute1": "got the data",
            "password": null,
            "*amzn-ddb-map-desc*": null,
            "attribute2": "got the data",
            "*amzn-ddb-map-sig*": null,
            "attribute3": "got the data",
            "attribute4": "got the data"
        },`

In the above result, the `password` , `*amzn-ddb-map-desc*`, `*amzn-ddb-map-sig*` are null, my crypto config is also same, I thought I would fetch this and decrypt with the inbuilt functions in encryption client, can anyone please help?

**Comment by josecorella** [comment]
Hello @Abutahir12!

Which version of the Dynamo Encryption Client are you using?
Also, would you mind sharing the code you used to get these null values both when you encrypt it with the encryptor and when you call get_item.
Please make sure to redact any account or sensitive information.

**Comment by alex-chew** [comment]
Hi @Abutahir12,

We haven't heard from you in a while so I'm going to close this issue for now. Please feel free to re-open it or open a new issue if you have more information/questions/concerns. Thanks!
