### ISSUE TITLE
typehints and imports

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-dynamodb-encryption-python#627]
Just wanted to let y'all know that you can remove stuff like this now that your minimum supported Python version is 3.7.

https://github.com/aws/aws-dynamodb-encryption-python/blob/e4dd5bf9e5733e413aa557e72d9e2abc939e26fd/src/dynamodb_encryption_sdk/structures.py#L25-L29

I put those in because the version of the `typing` library for specifically 3.5.0 and 3.5.1 only has a subset of the type definitions present for newer versions. Since the typehints are all in comments (another thing you can change now that you don't support 2.7 anymore), the imports were only necessary when running `mypy`, thus the `except: pass` rather than stubbing.

**Comment by khubaibalam2000** [comment]
Can I work on this issue?

**Comment by khubaibalam2000** [comment]
Resolved in #740.
