### ISSUE TITLE
Missing link on ProviderStore page of readthedocs

### ISSUE THREAD

**Issue by juneb** [aws/aws-dynamodb-encryption-python#80]
The **dynamodb_encryption_sdk.material_providers.store** string on the [ProviderStore readthedocs page](http://aws-dynamodb-encryption-python.readthedocs.io/en/latest/lib/materials_providers/provider_stores.html) is not linked to anything.

**Comment by texastony** [comment]
The store entry is referencing what Java would call an interface. 
The python documentation generator is doing us a solid by not creating a whole page for the abstract class.
If we wanted to author documentation on how to implement a Provider store, then that content would be linked there.
